reporting:
    print: none
    reports:
      - lcov
      - text-summary

instrumentation:
    root: ./client
    include-all-sources: true
    excludes:
      - "*.test.js"
      - main.js
      - plugins.js
      - ramda.js

